# Generated by Django 5.1.4 on 2025-01-20 19:45

import app.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', app.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mfa_enabled',
            field=models.BooleanField(null=True),
        ),
    ]
