# Generated by Django 5.1.4 on 2025-01-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_discorduser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='access_token',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='mfa_enabled',
            field=models.BooleanField(),
        ),
    ]
