# Generated by Django 5.1.4 on 2025-02-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='id',
        ),
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='quotes',
            name='quote',
            field=models.CharField(default=None, max_length=280),
        ),
        migrations.AddField(
            model_name='quotes',
            name='quote_id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='quotes',
            name='server_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date_quoted',
            field=models.DateField(default=None),
        ),
    ]
