# Generated by Django 5.1.4 on 2025-02-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_quotes_id_quotes_author_quotes_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
