# Generated by Django 5.1.4 on 2025-02-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quote_id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('server_id', models.CharField(default=None, max_length=20)),
                ('quote', models.CharField(default=None, max_length=280)),
                ('author', models.CharField(default=None, max_length=30)),
                ('date_quoted', models.DateField(default=None)),
            ],
        ),
    ]
