# Generated by Django 5.1.4 on 2025-02-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
